### ISSUE TITLE
useRefEffect

### ISSUE THREAD

**Issue by jantimon** [theKashey/use-callback-ref#6]
Hey @theKashey 

thanks a lot for your tiny helper 👍

I was wondering if it could make sense to provide a mix out of `useRefCallback` and `useEffect`

e.g.:

```js
const ref = useRefEffect((domElement) => {
    domElement.addEventListener(cb);
    return () => {
       domElement.removeEventListener(cb);
    }
});
```

The code might look like this:

```js
const useRefEffect = (refEffectCallback, dependencies) => {
  const cleanupCallback = useRef();
  // Make sure that the latest callback is fired:
  const effectCallbackRef = useRef(refEffectCallback);
  effectCallbackRef.current = refEffectCallback;
  // Create a new ref and wait for it to be populated
  return useRefCallback(null, (newValue, oldValue) => {
     // Cleanup the previous value
     if (oldValue && cleanupCallback.current) {
       cleanupCallback.current();
       cleanupCallback = undefined;
     }
     // Execute the callback and store the cleanup callback return from the effect
     cleanupCallback.current =  effectCallbackRef.current(newValue);
  });
}
``` 

maybe we could even allow dependencies e.g.:

```js
const ref = useRefEffect((domElement) => {
    domElement.addEventListener(cb);
    return () => {
       domElement.removeEventListener(cb);
    }
}, [cb]);
```

However an implementation without `useState` would probably be quite complicated.

**Comment by theKashey** [comment]
I see here 2 moments:
- an ability to have a cleanup callback
- the requirements to run effects in `useEffect` (not here)

```js
const [,update] = useState({});
const ref = useCallbackRef(ref, () => update({})); // trigger update on hook set
useEffect(() => {
 if(ref.current) {
  ref.current.addEventListener(cb);
    return () => {
       ref.current.removeEventListener(cb);
    }
 }
}, [ref.current]);
```

Thus
```js
const useRefEffect = (ref, effect) => {
  const [,update] = useState({});
  const ref = useCallbackRef(ref, () => update({})); 
  useEffect(() => {
   if(ref.current) {
    return effect(ref.current);
   }
  }, [ref.current]);
}
```

Should work. I'll double check implementation and the proper usage.
Well, I do use callbacks to run different effects, and those effects often __have__ to be wrapped with `useEffect`. Good catch.

**Comment by jantimon** [comment]
I see two disadvantages to your `useRefEffect` example:

1.  it would be less performant as it would require an additional rendering of the entire tree because you are setting a new state
2. `effect` might be outdated at the time you execute

that's why this implementation is using a ref to store always the latest `effect` inside `effectCallbackRef` and is not using `useState`:

```
const useRefEffect = (refEffectCallback, dependencies) => {
  const cleanupCallback = useRef();
  // Make sure that the latest callback is fired:
  const effectCallbackRef = useRef(refEffectCallback);
  effectCallbackRef.current = refEffectCallback;
  // Create a new ref and wait for it to be populated
  return useRefCallback(null, (newValue, oldValue) => {
     // Cleanup the previous value
     if (oldValue && cleanupCallback.current) {
       cleanupCallback.current();
       cleanupCallback = undefined;
     }
     // Execute the callback and store the cleanup callback return from the effect
     cleanupCallback.current =  effectCallbackRef.current(newValue);
  });
}
```

**Comment by jantimon** [comment]
hey @theKashey 

I published `useRefEffect` - if you find some time I would love to hear your feedback:

https://github.com/jantimon/react-use-ref-effect

- it is fully typed
- it doesn't require any additional render runs on DOM mount
- it provides an easy way for cleanup on unmount or ref target change (same api as `useEffect`)
- it supports dependencies (same api as `useEffect`)
- it allows using `ref.current`

```tsx
import { useRefEffect } from 'react-use-ref-effect';

const Component = () => {

  const ref = useRefEffect((element) => {
    console.log('Element', element, 'is now available');
    return () => {
      console.log('Element', element, 'is no longer available');
    }
  }, []);

  return <div ref={ref}>Hello World</div>
}
```

**Comment by theKashey** [comment]
Once one moment - there is no need (and no such pattern) to append object keys with `_`. Prepend - might be.

The rest seems to be valid 👍

**Comment by jantimon** [comment]
thanks for reviewing 👍

the strange `_` postfix is a pattern which allows advanced mangeling during minification:

https://esbuild.github.io/api/#mangle-props

https://terser.org/docs/cli-usage#cli-mangling-property-names-mangle-props

this minification is considered unsafe.  
for example minifying `className` in `const props = { className: 'foo' }` to `const t={d:'foo'}` would make it impossible for react to understand that you want to set a class name.

however especially small libs use this trick to save some bytes when it comes to internal properties minification 

the `_` postfix tells the mini für which properties are save for minification

**Comment by theKashey** [comment]
🤯 Today I Learned

In the past I was using `_` prefix for this, until eslint defaults broke this habit. `_` postfix makes sense 👍
